config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get '/about', to: 'welcome#about'
  resources :articles

  	get 'signup', to: 'users#new'
	resources :users, except: [:new]

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ApplicationRecord
has_many :articles, dependent: :destroy
before_save { self.email = email.downcase }
validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum:3, maximum: 25 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, uniqueness: true, length: { maximum: 50 }, format: VALID_EMAIL_REGEX
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user, :logged_in?

	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end	


	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
				flash[:danger] = "You must be logged in to perform that action"
				redirect_to root_path
		end
	end	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :article_set, only: [:destroy, :show, :edit, :update]
before_action :require_user, except: [:show, :index]
before_action :require_same_user, only: [:destroy, :edit, :update]

def new
	@article = Article.new
end

def show
	
end


def index

	@articles = Article.paginate(page: params[:page], per_page: 3)

end

def create

	@article = Article.new(article_params)
	@article.user = current_user
	if @article.save
		flash[:success] = 'The article was created'
		redirect_to article_path(@article)
	else
		render 'new'
	end	
end

def edit

end

def update
	if @article.update(article_params)
		flash[:success] = 'The article was updated'
		redirect_to article_path(@article)
	else
		render 'edit'
	end	
end

def destroy
	@article.destroy
	flash[:danger] = "Article was deleted"
	redirect_to articles_path
end

private

	def article_set
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, category_ids: [])
	end

	def require_same_user
		if current_user != @article.user and !current_user.admin?
			flash[:danger] = "You can perform actions only with your articles"
			redirect_to root_path
		end
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]
	before_action :admin_require, except: [:show, :index] 

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "The user #{@category.name} was created"
			redirect_to categories_path
		else
			render 'new'
		end
		
	end	

	def edit
		
	end

	def update
		if @category.update(category_params)
			flash[:success] = "The category #{@category.name} was updated"
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	def show
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
	end

	def index
		@categories = Category.paginate(page: params[:page], per_page: 3)
	end

	private
		def category_params
			params.require(:category).permit(:name)
		end

		def admin_require
			if !logged_in? || (logged_in? && !current_user.admin?)

			flash[:danger] = "Only admins can perform that action!"
			redirect_to categories_path
			end
		end
		def set_user
			@category = Category.find(params[:id])
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end

def create
	user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
		session[:user_id] = user.id
		flash[:success] = "Successfull login"
		redirect_to user_path(user)

	else
		flash.now[:danger] = "Something wrong"
		render 'new'
	end	

end

def destroy
	session[:user_id] = nil
	flash[:success] = "Successfull logout"
	redirect_to root_path
end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:destroy, :edit, :update]
	before_action :require_admin, only: [:destroy]
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "The user #{@user.username} was created"
			redirect_to user_path(@user)
		else
			render 'new'
		end	
	end	

	def edit

	end	

	def update

	if @user.update(user_params)
		flash[:success] = "The user #{@user.username} was updated"
		redirect_to articles_path
	else
		render 'edit'
	end	

	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
	end

	def index

		@users = User.paginate(page: params[:page], per_page: 3)
	end

	def destroy
		@user = User.find(params[:id])

			@user.destroy
			flash[:success] = "User #{@user.username} and all articles created by user have been deleted"
			redirect_to users_path
		end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end


	def set_user

	@user = User.find(params[:id])			

	end	


	def require_same_user
		if current_user != @user && !current_user.admin?
			flash[:danger] = "You can edit or delete only your user"
			redirect_to users_path
		end
	end

	def require_admin
		if logged_in? && !current_user.admin?
			flash[:danger] = "Only admin can perfom this action!"
			redirect_to root_path
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
    <% obj.each do |article|%>
        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="well well-lg">
                    <div class="article-title">
                        <%= link_to article.title, article_path(article) %>
                    </div>

                    <div class="article-body">
                        <%= truncate(article.description, length: 100) %>
                    </div>
                    <div class="article-meta-details">
						<small>Created by: <%= article.user.username if article.user%>,
							<%= time_ago_in_words(article.created_at) %> ago,
							last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
					</div>
                    <% if article.categories.any? %>
                        <p>Categories: <%= render article.categories %></p>
                    <% end %>

                    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                        <div class="article-actions">
                            <%= link_to 'Delete this article', article_path(article), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                                <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-sm btn-primary" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', object: @article%>
<%= form_for @article do |f|%>
    <div class="form-group row">
    <%= f.label :title, class: "col-sm-2 col-form-label", for: "inputTitle"%><br/>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control", id: "inputTitle"%>
    </div>
  </div>
      <div class="form-group row">
    <%= f.label :description, class: "col-sm-2 col-form-label", for: "inputDescription" %><br/>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control", rows: 10, id: "inputDescription" %>
    </div>
    </div>
  <div class="form-group row">
       <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
      </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <%= f.button class: "btn btn-primary btn-lg", type: "submit" %>
    </div>
  </div>

<% end %>

 <div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">There are all articles:</h1>

<!-- <%= link_to 'Create new article', new_article_path %> -->

<div align="center">
	<%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%=  @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
        <ul class="listing">
            <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                    <li>Created by:</li>
                    <li class="article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>
                    <li><small>
<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
</small></li>
                </div>
            </div>
        </ul>
        <% end %>
            <h4 class="center description"><strong>Description:</strong></h4>
            <hr>
            <%= simple_format(@article.description) %>
            <% if @article.categories.any? %>
                <p>Categories: <%= render @article.categories %></p>
            <% end %>
                <div class="article-actions">
	                <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
	                    <%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-sm btn-primary" %>
	                    <%= link_to 'Delete this article', article_path(@article), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
	                <% end %>
                            <%= link_to 'View all articles', articles_path, class: "btn btn-sm btn-success" %>
                </div>
</div>

app/views/categories/_category.html.erb
<%= link_to "#{category.name}", category_path(category), class: "badge badge-primary" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', object: @category%>
    <%= form_for @category do |f|%>
        <div class="form-group row">
            <%= f.label :name, class: "col-sm-2 col-form-label", for: "inputTitle"%>
                <br/>
                <div class="col-sm-10">
                    <%= f.text_field :name, placeholder: "Enter category name", class: "form-control", id: "inputTitle"%>
                </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-lg' %>
            </div>
        </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
        [<%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Caregories:</h1>
<div align="center">
<%= will_paginate%>
</div>
<ul class="list-group">
  <% @categories.each do |category|%>
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li class="article-title">
				<%= link_to "#{category.name}", category_path(category) %>
				</li>
				<li><small><%= pluralize(category.articles.count, "article") %></small></li>
				 <li> 
				  <% if logged_in? && current_user.admin? %>
  					<%= link_to "Delete", category_path(category), method: :delete, data: {confirm: "Are you sure?"} %>
  				<% end %>
  			</li>
			</div>
		</div>
	</ul>

<%end%>
</ul>
<div align="center">
<%= will_paginate%>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<div align="center">
	<% if logged_in? && current_user.admin? %>
	<div class="row">
<h2><%= link_to "Edit category", edit_category_path(@category), class: "badge badge-primary "%></h2>
</div>
<% end %>
	<%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
	<%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
 		<small>
 			Create by Mayhem
 		</small>
	 	<nav>
	 		<ul>
	 			<li>
	 				<%= link_to "About", about_path %>
	 			</li>
	 		</ul>		
	 	</nav>	
 	 </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="col-xs-10 col-xs-offset-1">
<div class='alert alert-<%="#{name}" %>' >
	<a href="#" class="close" data-dismiss="alert">×</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  
</div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                    <%= link_to "Users", users_path %>
                </li>
                <li>
                    <%= link_to "Articles", articles_path %>
                </li>    
                <% if logged_in? %>     
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <%= link_to "New Article", new_article_path %>
                        </li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
                <% end %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "All categories", categories_path %></li>
                        <% Category.all.each do |category| %>
                        <li>
                            <%= link_to "#{category.name}", category_path(category) %>
                        </li>
                        <% end %>
                        <% if logged_in? && current_user.admin? %>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "Create new category", new_category_path %></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            
            <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                <li><%= link_to "Log out", logout_path, method: :delete%></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
                        <li><%= link_to "View your profile", user_path(current_user) %></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Signup", signup_path %></li>
            <% end %>
            </ul>
           
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<%if object.errors.any?%>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading"><%= pluralize(object.errors.count, "error")%> prohibited this article from being saved:</h4>
  	<ul>
  		<% @article.errors.full_messages.each do |err_msg| %>
  		<li><%=err_msg%></li>
		<%end%>
	</ul>
</div>
<% end %>

app/views/shared/_errors_user.html.erb
<%if object.errors.any?%>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading"><%= pluralize(object.errors.count, "error")%> prohibited this article from being saved:</h4>
  	<ul>
  		<% @article.errors.full_messages.each do |err_msg| %>
  		<li><%=err_msg%></li>
		<%end%>
	</ul>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user%>
    <%= form_for @user do |f|%>
        <div class="form-group row">
            <%= f.label :username, class: "col-sm-2 col-form-label", for: "inputTitle"%>
                <br/>
                <div class="col-sm-10">
                    <%= f.text_field :username, placeholder: "Enter username", class: "form-control", id: "inputTitle"%>
                </div>
        </div>
        <div class="form-group row">
            <%= f.label :email, class: "col-sm-2 col-form-label", for: "inputDescription" %>
                <br/>
                <div class="col-sm-10">
                    <%= f.email_field :email, placeholder: "Enter email", class: "form-control", id: "inputDescription" %>
                </div>
        </div>

       <div class="form-group row">
            <%= f.label :password, class: "col-sm-2 col-form-label", for: "inputDescription" %>
                <br/>
                <div class="col-sm-10">
                    <%= f.password_field :password, placeholder: "Enter password", class: "form-control", id: "inputDescription" %>
                </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <%= f.button(@user.new_record? ? "Create new user" : "Update your user", class: "btn btn-primary btn-lg", type: "submit") %>
            </div>
        </div>
        <% end %>

            <div class="col-xs-4 col-xs-offset-4">
                [
                <%= link_to "Cancel request and return to articles listing", articles_path %> ]
            </div>

app/views/users/edit.html.erb
<h1 class="center">Update your account's data</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>List of users</h1>
<div align="center">
<%= will_paginate%>
</div>
<ul class="list-group">
  <% @users.each do |user|%>
  <li class="list-group-item d-flex justify-content-between align-items-center">
   <%= link_to user.username, user_path(user) %>
    <span class="badge badge-primary badge-pill"><%= user.articles.count%></span>
  </li>
  <% if logged_in? && current_user.admin? %>
  <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
<%end%>
</ul>
<div align="center">
<%= will_paginate%>
</div>

app/views/users/new.html.erb
<h1 class="center">Please create user</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="center">Articles of the <%= @user.username %></h1>
<div align="center">
<%= will_paginate @user_articles%>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div align="center">
<%= will_paginate @user_articles%>
</div>

app/views/welcome/about.html.erb
<h1>This is about page</h1>
<%= link_to image_tag('rails.png'), 'www.ruby.com' %>
<%= link_to 'Home', root_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1 class="display-4">Alpha blog</h1>
  <%= link_to "Sign up now", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

<!-- <%= link_to 'Alpha Blog', articles_path %> | <%= link_to 'About', about_path %> -->